name: Build go executable
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GO_VERSION: 1.17.7
    steps:
      - uses: actions/checkout@v2
      - name: Use go ${{ env.GO_VERSION }}
        uses: actions/setup-go@v2
        with:
          go-version: ${{ env.GO_VERSION }}
      - name: Build
        run: go build -o proot
      - name: Archive executable
        uses: actions/upload-artifact@v2
        with:
          name: proot
          path: |
            proot
