name: Build node executable
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      NODE_VERSION: 16.13.1
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: Install dependencies
        run: npm ci
      - name: Transpile ts
        run: npm run build
      - name: Make binary
        run:  npm run mkbin
      - name: Archive production artifacts
        uses: actions/upload-artifact@v2
        with:
          name: node single file executable
          path: |
            bin